# Generated by Django 3.1.3 on 2021-01-14 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210114_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(height_field=200, upload_to='media/', verbose_name='Изображение', width_field=200),
        ),
    ]
