# Generated by Django 3.1.3 on 2021-01-15 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210115_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='Дата публикации'),
        ),
    ]
